CREATE TABLE IF NOT EXISTS public.attempt
(
    date             date     NOT NULL,
    user_id          bigint   NOT NULL,
    coins_win        smallint NOT NULL DEFAULT 0,
    is_admin_accrued boolean  NOT NULL,
    is_win           boolean  NOT NULL,
    id               bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT attempt_pkey PRIMARY KEY (id),
    CONSTRAINT "user" FOREIGN KEY (user_id)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.attempt
    OWNER to postgres;

