CREATE TABLE IF NOT EXISTS public.attempt
(
    id               bigint   NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date             date     NOT NULL,
    "user"           bigint   NOT NULL,
    coins_win        smallint NOT NULL DEFAULT 0,
    is_admin_accrued boolean  NOT NULL,
    is_win           boolean  NOT NULL,
    CONSTRAINT attempt_pkey PRIMARY KEY (id)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.attempt
    OWNER to postgres;